Home work 1
notnan/taxi pull request #1
Opened 2020-11-22 18:22 UTC by notnan

2020-11-22 19:15 UTC, KustovAA requested changes

2020-11-22 19:15 UTC, KustovAA commented on src/App.js
> +    return <>{this.LAYOUTS[this.state.currentPage]}</>;
можно просто `return this.LAYOUTS[this.state.currentPage];`

2020-11-22 19:15 UTC, KustovAA commented on src/header/index.js
> +        <>
`<>` - лишняя, просто в  `<header>` можно завернуть

2020-11-22 19:15 UTC, KustovAA commented on src/login/index.js
> +    state = { currentPage: "login", currentSection: 'login' };
кажется currentPage никак не используется в этом компоненте

2020-11-22 19:15 UTC, KustovAA commented on src/mainPage/index.js
> +  state = { currentPage: "map" };
раз у тебя `SECTIONS`, назови поле в стейте `currentSection`

2020-11-22 19:15 UTC, KustovAA commented on src/App.js
> +  LAYOUTS = {
переименуй в `PAGES`, либо `currentPage` в `currentLayout`

2020-11-22 19:17 UTC, KustovAA commented on src/login/index.js
> +        console.log(section)
убери console.log

2020-11-23 03:23 UTC, notnan commented on src/header/index.js
> +        <>
исправлено

2020-11-23 03:23 UTC, notnan commented on src/mainPage/index.js
> +  state = { currentPage: "map" };
исправлено

2020-11-23 03:23 UTC, notnan commented on src/login/index.js
> +    state = { currentPage: "login", currentSection: 'login' };
исправлено

2020-11-23 03:23 UTC, notnan commented on src/login/index.js
> +        console.log(section)
убрал

2020-11-23 03:24 UTC, notnan commented on src/App.js
> +  LAYOUTS = {
готово

2020-11-23 09:22 UTC, KustovAA approved these changes

2020-11-23 09:22 UTC, merged